name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # main 브랜치에 push될 때
  workflow_run:
    workflows: ["Fetch News Data"]  # Fetch News Data 워크플로우가 완료된 후
    types:
      - completed
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Pull Latest Changes
        run: git pull origin main

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: |
          # news-data.json이 없는 경우 기본 데이터 생성
          [ -f public/news-data.json ] || echo '{"feed": []}' > public/news-data.json
          
          # sitemap.xml 날짜 업데이트
          current_date=$(date +%Y-%m-%d)
          sed -i "s/<lastmod>.*<\/lastmod>/<lastmod>$current_date<\/lastmod>/g" public/sitemap.xml
          
          npm run build
          
          # 빌드 후 sitemap.xml과 robots.txt가 build 폴더에 있는지 확인
          if [ ! -f build/sitemap.xml ] || [ ! -f build/robots.txt ]; then
            echo "Copying missing files to build directory..."
            cp -f public/sitemap.xml public/robots.txt build/ 2>/dev/null || true
          fi
        env:
          CI: false

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          commit_message: "Deploy: $(date)"
