name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["Fetch News Data"]
    types:
      - completed
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 모든 브랜치 정보 가져오기

      - name: Fetch news-data.json from news-data Branch
        run: |
          git fetch origin news-data
          git checkout origin/news-data -- public/news-data.json

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        env:
          REACT_APP_KAKAO_ADFIT_PC_ID: ${{ secrets.REACT_APP_KAKAO_ADFIT_PC_ID }}
        run: |
          current_date=$(date +%Y-%m-%d)
          sed -i "s/<lastmod>.*<\/lastmod>/<lastmod>$current_date<\/lastmod>/g" public/sitemap.xml
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          commit_message: "Deploy: $(date)"
