name: Fetch News and Deploy

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:  # Allow manual trigger
  push:
    branches: [ main ]  # Also run on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Fetch News Data
        continue-on-error: true  # API 요청 실패해도 워크플로우 계속 실행
        run: |
          mkdir -p public
          
          # API 키가 없을 경우 기존 데이터 유지
          if [[ -z "${{ secrets.ALPHA_VANTAGE_API_KEY }}" ]]; then
            echo "API key is missing! Keeping existing data."
          else
            # API 요청을 통해 뉴스 데이터 가져오기
            response=$(curl -s -X GET "https://www.alphavantage.co/query?function=NEWS_SENTIMENT&topics=economy_fiscal&apikey=${{ secrets.ALPHA_VANTAGE_API_KEY }}")
            
            # JSON에서 "feed" 필드 확인
            if echo "$response" | jq -e '.feed' > /dev/null 2>&1; then
              echo "$response" > public/news-data.json
              echo "✅ Successfully fetched and updated news data at $(date)"
            else
              echo "⚠️ API response does not contain 'feed'. Keeping existing data."
            fi
          fi
          
          # news-data.json이 없으면 기본 JSON 생성
          [ -f public/news-data.json ] || echo '{"feed": []}' > public/news-data.json

      - name: Build Project
        run: npm run build
        env:
          CI: false

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          commit_message: "Deploy and update news data: $(date)"
