name: Fetch News Data

on:
  schedule:
    - cron: '0 * * * *'  # 매 시간 정각마다 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout news-data Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: news-data  # ✅ `news-data` 브랜치를 체크아웃

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Fetch News Data
        id: fetch-news
        run: npm run fetch-news
        env:
          ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}

      - name: Commit and Push Changes to news-data Branch
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add public/news-data.json
          git commit -m "Update news data: $(date)" || echo "No changes to commit"
          git push origin news-data  # ✅ `news-data` 브랜치에 푸시!
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
