name: Fetch News Data

on:
  schedule:
    - cron: '*/30 * * * *'  # 매 30분마다 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Fetch News Data
        id: fetch-news
        run: npm run fetch-news
        env:
          ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}

      - name: Upload News Data as Artifact
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: news-data
          path: public/news-data.json
